config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'users#index'
  get 'logout' => 'users#logout'

  resources :users, only: [:show, :destroy]
  resources :movies

  namespace :api do
    namespace :v1 do
    	get 'find_user_or_create' => 'favmovies#find_user_or_create'
    	get 'movies' => 'favmovies#movies'
    	get 'detail_movie' => 'favmovies#detail_movie'
    	get 'user_movies' => 'favmovies#user_movies'
    	get 'do_favorite' => 'favmovies#do_favorite'
    end
  end  	
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :user_movies
  has_many :users, through: :user_movies

  serialize :genre, Array
  GENRE = ["Action","Adventure","Animation","Biography", "Comedy", "Crime", "Documentary", "Drama", "Fantasy", "History" ,"Horror", "Musical", "Mystery", "Romance", "Sci-Fi", "Thriller", "War", "Western"]
end

app/models/user.rb
class User < ApplicationRecord
	has_many :user_movies
	has_many :movies, through: :user_movies
end

app/models/user_movie.rb
class UserMovie < ApplicationRecord
	belongs_to :user
	belongs_to :movie
end

app/controllers/api/v1/favmovies_controller.rb
class Api::V1::FavmoviesController < ApplicationController
  before_action :find_movie, only: %i[detail_movie do_favorite]
  before_action :find_user, only: %i[user_movies do_favorite]

  def find_user_or_create
  	user = User.find_by(username: user_name)
  	if user
  		render json: "Login successfully"
  	else
      User.create(username: user_name)
  		render json: "User created and login"	
  	end
  end

  def movies
    render json: all_movies
  end

  def detail_movie
    if @movie
      render json: @movie
    else
      render json: "Not found"
    end  
  end

  def do_favorite
    if @user && @movie
      create_movie
      @movie.fav_users = @movie.fav_users + 1
      @movie.save
      render json: "successfully marked"
    else  
      render json: "Not found"
    end
  end

  def user_movies
    if @user
      render json: @user.movies
    else
      render json: "Not found"
    end  
  end

  private

  def user_name
    params[:name]
  end

  def all_movies
    Movie.all
  end

  def find_movie
    @movie = Movie.find_by(id: params[:id])
  end

  def find_user
    @user = User.find_by(id: params[:user_id])
  end

  def create_movie
    UserMovie.create!(movie_id: @movie.id, user_id: @user.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate

	def authenticate
	  authenticate_or_request_with_http_basic('Administration') do |email, password|
	    email == 'diego@scissorboy.com' && password == '123456'
	  end
	end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :find_movie, only: %i[edit destroy update]

  def index
    @movies = Movie.all
  end

  def create
    movie = Movie.new(movie_params)
    if movie.save
      redirect_to movies_path
    else
      render :new 
    end   
  end

  def new
    @movie = Movie.new
  end

  def edit
  end

  def update
    if @movie.update(movie_params)
      redirect_to movies_path
    else
      render :new 
    end
  end

  def destroy
    if @movie.destroy
      redirect_to movies_path
    else
      render :edit 
    end
  end

  private

  def find_movie
    @movie = Movie.find_by(id: params[:id])
  end

  def movie_params
    params.require(:movie).permit(:name, :year, :director, :main_star, :description, genres: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: %i[show destroy]
  def index
    @users = User.all
  end

  def show; end

  def destroy
    @user.destroy
    redirect_to admin_path
  end

  def logout; end

  private
  def find_user
    @user = User.find_by(id: params[:id])
  end
end

app/helpers/api/v1/favmovies_helper.rb
module Api::V1::FavmoviesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper

  def checked(value)
    if @movie.genres 
      @movie.genres.include?value
    else
      false
    end    
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieaFav</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

  </body>
</html>

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true %><br><br>
  <% Movie::GENRE.each do |v| %>

      <%= f.check_box(:genres, { :multiple => true, checked: checked(v) }, v) %>
       <%= f.label :genres, v.humanize %>
  <% end %><br><br>
  <%= f.select :year, (1900..2019), required: true %><br><br>

  <%= f.label :director %>
  <%= f.text_field :director %><br><br>

  <%= f.label :main_star %>
  <%= f.text_field :main_star %><br><br>

  <%= f.label :description %>
  <%= f.text_field :description %><br><br>

  <%= f.submit %>
  <%= link_to "Back", movies_path %>
<% end %>

app/views/movies/edit.html.erb
<%= render "form" %>

app/views/movies/index.html.erb
<%= link_to "Logout", logout_path %><br><br>
<%= link_to "Movies", movies_path %>
<%= link_to "Users", admin_path, class: "decoration_none"%>

<br><br>
<%= link_to "Add Movie", new_movie_path %>
<br><br><br>
<table>
  <% @movies.each do |movie| %>
    <tr>
    <td><%= link_to movie.name, edit_movie_path(movie) %></td>
    <td><%= movie.year %></td>
    <td><%= movie.users.count %></td>
    <td><%= link_to "Delete", movie_path(movie.id), method: :delete %></td>
    </tr>  
  <% end %>
</table>

app/views/movies/new.html.erb
<%= render "form" %>

app/views/users/delete.html.erb
<h1>Users#delete</h1>
<p>Find me in app/views/users/delete.html.erb</p>

app/views/users/index.html.erb
<%= link_to "Logout", logout_path %><br><br>
<%= link_to "Movies", movies_path, class: "decoration_none" %>
<%= link_to "Users", admin_path %>
<br><br><br>
<table>
  <% @users.each do |user| %>
    <tr>
    <td><%= link_to user.username, user_path(user.id) %></td>
    <td><%= user.movies.count %></td>
    <td><%= link_to "Delete", user_path(user.id), method: :delete %></td>
    </tr>  
  <% end %>
</table>

app/views/users/logout.html.erb
<h1>Thank you, You are successfully logged out</h1>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>
<h1>3</h1>
<h1><%= link_to "Back", admin_path %></h1>